name: digitalocean-docker-nextjs
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: loyep/digitalocean-docker-nextjs
  name: digitalocean-docker-nextjs
